set_property PACKAGE_PIN N15 [get_ports clk]
set_property PACKAGE_PIN J2 [get_ports reset_rtl_0]
set_property PACKAGE_PIN G1 [get_ports {sw_i[0]}]
set_property PACKAGE_PIN F2 [get_ports {sw_i[1]}]
set_property PACKAGE_PIN F1 [get_ports {sw_i[2]}]
set_property PACKAGE_PIN E2 [get_ports {sw_i[3]}]
set_property PACKAGE_PIN E1 [get_ports {sw_i[4]}]
set_property PACKAGE_PIN D2 [get_ports {sw_i[5]}]
set_property PACKAGE_PIN D1 [get_ports {sw_i[6]}]
set_property PACKAGE_PIN C2 [get_ports {sw_i[7]}]
set_property PACKAGE_PIN B2 [get_ports {sw_i[8]}]
set_property PACKAGE_PIN A4 [get_ports {sw_i[9]}]
set_property PACKAGE_PIN A5 [get_ports {sw_i[10]}]
set_property PACKAGE_PIN A6 [get_ports {sw_i[11]}]
set_property PACKAGE_PIN C7 [get_ports {sw_i[12]}]
set_property PACKAGE_PIN A7 [get_ports {sw_i[13]}]
set_property PACKAGE_PIN B7 [get_ports {sw_i[14]}]
set_property PACKAGE_PIN A8 [get_ports {sw_i[15]}]
set_property PACKAGE_PIN L18 [get_ports Servo1PWM]
set_property PACKAGE_PIN M14 [get_ports Servo2PWM]
set_property PACKAGE_PIN J15 [get_ports i2c_scl]
set_property PACKAGE_PIN J16 [get_ports i2c_sda]
set_property PACKAGE_PIN K14 [get_ports camera_vsync]
set_property PACKAGE_PIN K16 [get_ports camera_href]
set_property PACKAGE_PIN H17 [get_ports camera_clock]
set_property PACKAGE_PIN F15 [get_ports camera_pixel_clock]
set_property PACKAGE_PIN H18 [get_ports {camera_datain[7]}]
set_property PACKAGE_PIN H16 [get_ports {camera_datain[6]}]
set_property PACKAGE_PIN E16 [get_ports {camera_datain[5]}]
set_property PACKAGE_PIN G16 [get_ports {camera_datain[4]}]
set_property PACKAGE_PIN C12 [get_ports {camera_datain[3]}]
set_property PACKAGE_PIN C11 [get_ports {camera_datain[2]}]
set_property PACKAGE_PIN D11 [get_ports {camera_datain[1]}]
set_property PACKAGE_PIN D10 [get_ports {camera_datain[0]}]
set_property PACKAGE_PIN E15 [get_ports pwdn]
set_property PACKAGE_PIN U16 [get_ports hdmi_tmds_clk_p]
set_property PACKAGE_PIN V17 [get_ports hdmi_tmds_clk_n]
set_property PACKAGE_PIN U17 [get_ports {hdmi_tmds_data_p[0]}]
set_property PACKAGE_PIN U18 [get_ports {hdmi_tmds_data_n[0]}]
set_property PACKAGE_PIN R16 [get_ports {hdmi_tmds_data_p[1]}]
set_property PACKAGE_PIN R17 [get_ports {hdmi_tmds_data_n[1]}]
set_property PACKAGE_PIN R14 [get_ports {hdmi_tmds_data_p[2]}]
set_property PACKAGE_PIN T14 [get_ports {hdmi_tmds_data_n[2]}]
set_property PACKAGE_PIN H14 [get_ports camera_reset_sig]
set_property IOSTANDARD LVCMOS33 [get_ports {camera_datain[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {camera_datain[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {camera_datain[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {camera_datain[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {camera_datain[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {camera_datain[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {camera_datain[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {camera_datain[0]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw_i[15]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw_i[14]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw_i[13]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw_i[12]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw_i[11]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw_i[10]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw_i[9]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw_i[8]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw_i[7]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw_i[6]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw_i[5]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw_i[4]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw_i[3]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw_i[2]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw_i[1]}]
set_property IOSTANDARD LVCMOS25 [get_ports {sw_i[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports Servo1PWM]
set_property DRIVE 16 [get_ports Servo1PWM]
set_property SLEW SLOW [get_ports Servo1PWM]
set_property IOSTANDARD LVCMOS33 [get_ports Servo2PWM]
set_property DRIVE 16 [get_ports Servo2PWM]
set_property SLEW SLOW [get_ports Servo2PWM]
set_property IOSTANDARD LVCMOS33 [get_ports i2c_sda]
set_property DRIVE 12 [get_ports i2c_sda]
set_property SLEW SLOW [get_ports i2c_sda]
set_property IOSTANDARD LVCMOS33 [get_ports camera_href]
set_property IOSTANDARD LVCMOS33 [get_ports camera_pixel_clock]
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets camera_pixel_clock_IBUF]
set_property IOSTANDARD LVCMOS33 [get_ports camera_reset_sig]
set_property DRIVE 12 [get_ports camera_reset_sig]
set_property SLEW SLOW [get_ports camera_reset_sig]
set_property IOSTANDARD LVCMOS33 [get_ports camera_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports pwdn]
set_property DRIVE 12 [get_ports pwdn]
set_property SLEW SLOW [get_ports pwdn]
set_property IOSTANDARD LVCMOS33 [get_ports i2c_scl]
set_property DRIVE 12 [get_ports i2c_scl]
set_property SLEW SLOW [get_ports i2c_scl]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_tmds_data_n[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_tmds_data_n[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_tmds_data_n[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_tmds_data_p[2]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_tmds_data_p[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_tmds_data_p[0]}]
set_property IOSTANDARD TMDS_33 [get_ports hdmi_tmds_clk_n]
set_property IOSTANDARD TMDS_33 [get_ports hdmi_tmds_clk_p]
set_property IOSTANDARD LVCMOS25 [get_ports reset_rtl_0]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports camera_clock]
set_property DRIVE 12 [get_ports camera_clock]
set_property SLEW SLOW [get_ports camera_clock]

set_property PACKAGE_PIN N15 [get_ports clkin]
set_property IOSTANDARD LVCMOS33 [get_ports clkin]



connect_debug_port u_ila_0/probe1 [get_nets [list {target/maxInd_reg[0]_0}]]
connect_debug_port u_ila_0/probe2 [get_nets [list {target/maxInd_reg[0]_1}]]


connect_debug_port u_ila_0/probe6 [get_nets [list target/vsync]]


set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports uart_rtl_0_txd]
set_property PACKAGE_PIN B16 [get_ports uart_rtl_0_rxd]
set_property PACKAGE_PIN A16 [get_ports uart_rtl_0_txd]

set_property OFFCHIP_TERM NONE [get_ports Servo1PWM]
set_property OFFCHIP_TERM NONE [get_ports Servo2PWM]
set_property OFFCHIP_TERM NONE [get_ports camera_clock]
set_property OFFCHIP_TERM NONE [get_ports camera_reset_sig]
set_property OFFCHIP_TERM NONE [get_ports i2c_scl]
set_property OFFCHIP_TERM NONE [get_ports i2c_sda]
set_property OFFCHIP_TERM NONE [get_ports pwdn]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_wiz_1/inst/clk_out2]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 14 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {blk_design/gpio_rtl_0_tri_i[3]} {blk_design/gpio_rtl_0_tri_i[4]} {blk_design/gpio_rtl_0_tri_i[5]} {blk_design/gpio_rtl_0_tri_i[6]} {blk_design/gpio_rtl_0_tri_i[7]} {blk_design/gpio_rtl_0_tri_i[8]} {blk_design/gpio_rtl_0_tri_i[9]} {blk_design/gpio_rtl_0_tri_i[19]} {blk_design/gpio_rtl_0_tri_i[20]} {blk_design/gpio_rtl_0_tri_i[21]} {blk_design/gpio_rtl_0_tri_i[22]} {blk_design/gpio_rtl_0_tri_i[23]} {blk_design/gpio_rtl_0_tri_i[24]} {blk_design/gpio_rtl_0_tri_i[25]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 7 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {tarY[3]} {tarY[4]} {tarY[5]} {tarY[6]} {tarY[7]} {tarY[8]} {tarY[9]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 7 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {tarX[3]} {tarX[4]} {tarX[5]} {tarX[6]} {tarX[7]} {tarX[8]} {tarX[9]}]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets camera_clock_OBUF]
